import { execFileSync } from "node:child_process";
import { mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.dirname(fileURLToPath(import.meta.url)) + "/..";
const inputPath = path.join(root, "src/css/tailwind-input.css");
const generatedDir = path.join(root, "src/generated");
const tailwindBin = path.join(root, "node_modules/.bin/tailwindcss");
const tmpOutput = path.join(tmpdir(), `ftle-tailwind-${process.pid}.css`);

mkdirSync(generatedDir, { recursive: true });

execFileSync(tailwindBin, ["-i", inputPath, "-o", tmpOutput, "--minify"], {
  cwd: root,
  stdio: "inherit",
});

const css = readFileSync(tmpOutput, "utf8").trim();
rmSync(tmpOutput, { force: true });

writeFileSync(
  path.join(generatedDir, "site-css.ts"),
  `// Generated by scripts/build-css.mjs — do not edit.\nexport const SITE_CSS = ${JSON.stringify(css)};\n`,
);

console.log(`prepare:css — wrote src/generated/site-css.ts (${css.length} bytes)`);
